name: Security Vulnerability
description: Report a security vulnerability
title: "[SECURITY] "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a security vulnerability. Please review our [Security Policy](SECURITY.md) for more information on how we handle security issues.

        If you are reporting a security vulnerability, please provide as much detail as possible so we can assess and address it promptly.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief description of the security issue.
      placeholder: "Describe the security vulnerability in a few sentences."
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Vulnerability Details
      description: Detailed description of the vulnerability, including how it can be exploited.
      placeholder: "Provide detailed steps, code snippets, or other information that demonstrates the vulnerability."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact of this vulnerability?
      placeholder: "Describe the potential consequences if this vulnerability is exploited."
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Any suggestions for fixing or mitigating the issue.
      placeholder: "Provide any suggestions for how to fix or mitigate this vulnerability."

  - type: input
    id: contact
    attributes:
      label: Contact Information (Optional)
      description: How can we contact you for more information?
      placeholder: "Email address or other contact method"

  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this issue, you agree to our responsible disclosure terms.
      options:
        - label: I understand that this is a private security report and will not publicly disclose details until the issue is resolved.
          required: true