name: Support Request
description: Request help or support
title: "[SUPPORT] "
labels: ["support"]
body:
  - type: markdown
    attributes:
      value: |
        If you need help or support with using the launcher, please fill out this support request.
        Provide as much detail as possible so we can assist you effectively.
        **Need a quick assistance?** Please Open-A-Ticket in our [Discord Server](https://discord.gg/gME8rUy3MB)!

  - type: textarea
    id: question
    attributes:
      label: What do you need help with?
      description: Describe your question or issue clearly.
      placeholder: "I'm having trouble with..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or background information.
      placeholder: "I've tried..., but got..."
    validations:
      required: true

  - type: textarea
    id: hardwarespec
    attributes:
      label: Hardware Specification
      description: Tell us your CPU, iGPU, dGPU, VRAM, and RAM information.
      placeholder: "CPU: Intel i9-14900K 6.0 GHz | GPU: NVIDIA RTX 4090 | VRAM: 24 GB | RAM: 32 GB"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
      placeholder: "e.g. v2.0.11 stable/pre-release"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you using?
      options:
        - Windows 10
        - Windows 11
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux Ubuntu/Debian-based
        - Linux Fedora/RHEL-based
        - Linux Arch-based
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: If applicable, paste any error messages or logs here.
      render: shell
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might help us assist you.
